# Generated by Django 3.1.1 on 2021-05-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.ManyToManyField(to='myapp.Signup'),
        ),
    ]
