# Generated by Django 3.1.1 on 2021-05-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_otpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.BooleanField(),
        ),
    ]
