# Generated by Django 3.1.1 on 2021-05-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210506_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
