# Generated by Django 3.1.1 on 2021-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210506_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
